### ISSUE TITLE
dumpclass时报java.lang.reflect.InvocationTargetException错误

### ISSUE THREAD

**Issue by LifeHackerBee** [hengyunabc/dumpclass#10]
在使用`java -jar .\dumpclass.jar -p 26532 com.restful.demo.* -o D:\dump --classLoaderPrefix`参数dump class时报如下错误，请问该如何解决，谢谢！
```
PS D:\QA\AOP-toolbox\tools\dumpclass> java -jar .\dumpclass.jar -p 26532 com.restful.demo.* -o D:\dump --classLoaderPrefix
can not find sa-jdi.jar from classpath, try to load it from java.home.
Attaching to process ID 26532, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.231-b11
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.github.hengyunabc.dumpclass.DumpMain$2.run(DumpMain.java:184)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.github.hengyunabc.dumpclass.DumpMain.run(DumpMain.java:132)
        at io.github.hengyunabc.dumpclass.DumpMain.doMain(DumpMain.java:68)
        at io.github.hengyunabc.dumpclass.DumpMain.main(DumpMain.java:61)
        ... 6 more
Caused by: java.lang.InternalError
        at sun.jvm.hotspot.tools.jcore.ClassWriter.writeIndex(ClassWriter.java:106)
        at sun.jvm.hotspot.tools.jcore.ClassWriter.writeMethod(ClassWriter.java:550)
        at sun.jvm.hotspot.tools.jcore.ClassWriter.writeMethods(ClassWriter.java:431)
        at sun.jvm.hotspot.tools.jcore.ClassWriter.write(ClassWriter.java:93)
        at io.github.hengyunabc.dumpclass.DumpWrapperFilter.dumpKlass(DumpWrapperFilter.java:99)
        at io.github.hengyunabc.dumpclass.DumpWrapperFilter.canInclude(DumpWrapperFilter.java:31)
        at sun.jvm.hotspot.tools.jcore.ClassDump.dumpKlass(ClassDump.java:138)
        at sun.jvm.hotspot.tools.jcore.ClassDump.access$000(ClassDump.java:38)
        at sun.jvm.hotspot.tools.jcore.ClassDump$1.visit(ClassDump.java:109)
        at sun.jvm.hotspot.memory.Dictionary.classesDo(Dictionary.java:68)
        at sun.jvm.hotspot.memory.SystemDictionary.classesDo(SystemDictionary.java:190)
        at sun.jvm.hotspot.tools.jcore.ClassDump.run(ClassDump.java:105)
        at sun.jvm.hotspot.tools.Tool.startInternal(Tool.java:260)
        at sun.jvm.hotspot.tools.Tool.start(Tool.java:223)
        at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
        at sun.jvm.hotspot.tools.jcore.ClassDump.main(ClassDump.java:180)
        ... 13 more
```

**Comment by hengyunabc** [comment]
试下只精确一个类，也可能是jdk本身的bug，试下升到最新的。
