### ISSUE TITLE
当有重名类时，会出错

### ISSUE THREAD

**Issue by hengyunabc** [hengyunabc/dumpclass#2]
```
sudo java -jar target/dumpclass.jar 53577 *StringUtils
can not find sa-jdi.jar from classpath, try to load it from java.home.
Attaching to process ID 53577, please wait...
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at io.github.hengyunabc.dumpclass.DumpMain.main(DumpMain.java:101)
Caused by: java.lang.InternalError: void* type hasn't been seen when parsing int*
    at sun.jvm.hotspot.HotSpotTypeDataBase.recursiveCreateBasicPointerType(HotSpotTypeDataBase.java:721)
    at sun.jvm.hotspot.HotSpotTypeDataBase.lookupType(HotSpotTypeDataBase.java:134)
    at sun.jvm.hotspot.HotSpotTypeDataBase.lookupOrCreateClass(HotSpotTypeDataBase.java:631)
    at sun.jvm.hotspot.HotSpotTypeDataBase.createType(HotSpotTypeDataBase.java:751)
    at sun.jvm.hotspot.HotSpotTypeDataBase.readVMTypes(HotSpotTypeDataBase.java:195)
    at sun.jvm.hotspot.HotSpotTypeDataBase.<init>(HotSpotTypeDataBase.java:89)
    at sun.jvm.hotspot.HotSpotAgent.setupVM(HotSpotAgent.java:403)
    at sun.jvm.hotspot.HotSpotAgent.go(HotSpotAgent.java:305)
    at sun.jvm.hotspot.HotSpotAgent.attach(HotSpotAgent.java:140)
    at sun.jvm.hotspot.tools.Tool.start(Tool.java:185)
    at sun.jvm.hotspot.tools.Tool.execute(Tool.java:118)
    at sun.jvm.hotspot.tools.jcore.ClassDump.main(ClassDump.java:180)
    ... 5 more
```

**Comment by hengyunabc** [comment]
这个出错是因为jdk版本不一致，并不是因为有重名类。

但是还是有类重名的问题。目前是只会dump出一份class。

**Comment by hengyunabc** [comment]
要考虑怎么比较好的支持多个classloader的情况。
- 把dump出来的类，放到不同的路径下去？比如 XXXClassLoader@55c32d 这样子的命名
- 是否考虑查看当前所有的classloader的情况，列出某个classloader 加载了哪些类

**Comment by hengyunabc** [comment]
done.
